server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${rds.username}
    password: ${rds.password}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.id}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

    #  redis:
    #    host: localhost
    #    port: 6379

jwt:
  secretKey: "dkfjklfdfdadfadf23f24f30298nf2ndkfjld2jkflddfa3fdf2fe43fejl34fklje23kj"
  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: "Authorization"
  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: "Authorization-refresh"

cloud:
  aws:
    s3:
      bucket: waste-photos
    credentials:
      access-key: ${greenwalk.accesskey}
      secret-key: ${greenwalk.secretkey}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    '[org.springframework.boot.web]': INFO

flask:
  url: ${flask.url}